language: php

php:      5.5

before_script:
    - composer self-update
    - travis_retry composer install --dev --prefer-dist

    - chmod -R 777 app/cache app/logs

script:
    - bin/phpspec run -fpretty --verbose
    - bin/behat --no-snippets --verbose --tags="~openvz"
