language: php

php:      5.4

services:
    - mongodb
    - rabbitmq

before_script:
    - chmod -R 777 app/cache app/logs

script:
    - bin/check-cs
    - bin/phpspec run -fpretty --verbose
    - bin/behat --no-snippets --verbose --tags="~openvz"